plugins {
    id 'fabric-loom' version '1.10-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url "https://api.modrinth.com/maven" }
    maven { url "https://maven.isxander.dev/releases" }
}

fabricApi {
    configureDataGeneration()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"

    include(modImplementation("maven.modrinth:ducky-updater-lib:${project.ducky_updater}"))
    include(modImplementation("maven.modrinth:fstats:${project.fstats}"))
}

processResources {
    inputs.property "version", project.version
    inputs.property "fabricloader", project.loader_version
    inputs.property "fabric_api", project.fabric_version
    inputs.property "minecraft", project.minecraft_version
    inputs.property "java", JavaVersion.VERSION_21
    inputs.property "fstats_version", project.fstats
    inputs.property "ducky_updater_version", project.ducky_updater


    filesMatching("fabric.mod.json") {
        expand "version": project.version
        expand "fabricloader": project.loader_version
        expand "fabric_api": project.fabric_version
        expand "minecraft": project.minecraft_version
        expand "java": JavaVersion.VERSION_21
        expand "fstats_version": project.fstats
        expand "ducky_updater_version": project.ducky_updater
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
    repositories {
    }
}