org.gradle.jvmargs=-Xmx4G
# Fabric Properties
minecraft_version=1.21.6
yarn_mappings=1.21.6+build.1
loader_version=0.18.4
# Mod Properties
mod_version=1.21.6-1.0
maven_group=net.valion
archives_base_name=ManyFlowers
# Dependencies
fabric_version=0.128.2+1.21.6
yacl_version=3.8.2+1.21.6-fabric
ducky_updater=2025.6.1
fstats=GbjJaFoz
kotlin_fabric=1.13.9+kotlin.2.3.10
modmenu_version=15.0.0